### ISSUE TITLE
Missing GEMlib

### ISSUE THREAD

**Issue by miniupnp** [mikrosk/m68k-atari-mint-build#7]
GEMlib is missing, right ? :)

**Comment by miniupnp** [comment]
But I guess I will try to fix #4 before ;)

**Comment by mikrosk** [comment]
Actually, this is a feature. My usual workflow on new machine is: compile binutils+gcc+mintlib+mintbin and then do cvs checkout for `freemint` + `libs` projects. And `libs` = gemlib, cflib, gemma. 

To make my life easier, I have https://github.com/mikrosk/m68k-atari-mint-devel which already contains `libs` so that's the reason why I don't have it here.

**Comment by miniupnp** [comment]
maybe that should be written in the README ;)

**Comment by mikrosk** [comment]
Maybe. :) It depends what do you expect from the toolchain, my idea was always to get a clean system -- ideally I would include just FreeMiNT includes, if there were something like that (similar to `linux-headers`).
